#-------------------------------
# General Site Settings

title: RITSEC
title_long: RITSEC Student Computing Security Club
motto: Security Through Community
email: ritsecclub@gmail.com
description: >
  RITSEC Student Computing Security Club
twitter: RITSECclub
github: 
  name: ritsec
  project: ritsec.github.io
facebook_page: RITSEC
facebook_group: RITSEC.group
youtube: UCfakBry_pXOvaPrVVr1SH-Q

#-------------------------------
# Main Image Slider Settings
slider:
  - image: ISTS_0.jpg
  - image: ISTS_1.jpg
  - image: ISTS_2.jpg
  - image: ISTS_3.jpg
  - image: ISTS_4.jpg
  - image: ISTS_5.jpg

#-------------------------------
# Navbar Settings
favicon: favicon.png
navbar-brand:
  image: logo_header.png
  link: '/index.html'

navbar:
  - name: 'Home'
    link: 'index.html'
  - name: 'About'
    link: 'about.html'
  - name: Members
    link: 'eboard.html'
    subitems:
    - name: 'EBoard'
      link: 'eboard.html'
    - name: 'Past EBoards'
      link: 'past-eboards.html'
    - name: 'Alumni'
      link: 'alumni.html'
  - name: 'Events'
    link: 'events.html'
  - name: 'Sponsors'
    link: 'sponsors.html'

#-------------------------------
# EBoard Settings

eboard_roles:
  - name: President
    appointee: Micah Martin
    image: micah.jpg
    description: >
      Micah Martin is a fourth-year Computing Security student at RIT. He is captain of RITSEC's
      Red team and loves helping with and competing in security 
      competitions. Micah's technical focus is primary on Linux systems and redteam malware. He loves helping out
      the community, learning with others, and answering questions. If he isn't sleeping in the computer labs,
      he can be found sleeping out in the woods.

  - name: Head of Education
    appointee: Russell Babarsky
    image: hoe.jpg
    description: >
      Russell Babarsky is a fourth-year Computing Security major. His passion lies 
      in pen testing and exploit development. Besides security, he enjoys hiking, 
      baseball, and listening to music.
  - name: Head of Research
    appointee: Nick O'Brien
    image: nick.jpg
    description: >
      Nick is a graduate Computing Security student. He in his off time does the cryptography and some product security.
      Usually he resides in the labs until sleep beckons unto him. Reach out and talk with him about Math, Coding,
      Politics, Alcohol, or just about anything!
  - name: Competition Architect
    appointee: Sean Newman
    image: sean.jpg
    description: >
      Sean is a BS/MS Computing Security student in his Junior year at RIT. He spends most of his time in the labs
      or at home messing about with servers. When he gets a rare chance to do something else, he enjoys rowing, cooking,
      and taking long naps. If you see him in the labs, talk to him about homelabbing, what he last cooked for dinner, and
      how to sleep pretty much anywhere.
  - name: Treasurer
    appointee: Shannon McHale
    image: shannon.jpg
    description: >
      Shannon is a second year computing security student with a minor in criminal justice.
      She was formally treasurer of RC3 and is currently the Public Relations Committee Head of Women in Computing.
      In her free time, Shannon tries to find free ways to attend security conferences.
  - name: Secretary
    appointee: Jack McKenna
    image: jack.jpg
    description: >
      Jack lives in the labs. If you need to get ahold of him just wander around and you'll run into him. He's usually buried
      deep in his computer working on a new project. He is always happy to answer questions about security or just life in general.
  - name: Director of Public Relations
    appointee: Alicen Dipiano
    image: alicen.jpg
    description: >
      Alicen is a junior Computing Security student. She enjoys reading about very niche markets in security which mainly
      focus on the Security in unusual practices which at the moment is the effects and lacking security of embedded biomedical
      devices. She tends to be found stress baking or cooking at odd hours in the morning or Swing dancing at Lindy Jam or with
      the Brick City Boppers. If you ever need to find her, you'll be able to hear her before you see her. Feel Free to say hi!
  - name: Operations Lead
    appointee: Brandon Adler
    image: brandon.jpg
    description: >
      Brandon is a fourth-year BS/MS in Computing Security. He enjoys learning new things, spending time with friends, and
      hanging out at the lake during the summer.
  - name: Tech Lead
    appointee: Scott Brink
    image: scott.jpg
    description: >
      Scott is a senior Computing Security student. He is part of the varsity swim team and loves to rock climb.
      You can find him in the labs yelling at his computer and drinking way too much monster, wearing one of his
      hundreds of hoodies. Always open to talking about your favorite dank memes.

#-------------------------------
# About Us

about_us_short: >
  <p>RITSEC is a student-run organization dedicated to educating and preparing RIT students to compete in security-related
  competitions, as well as showcasing RIT student talent in the current world of security today.</p>
about_us_long: >
  <br><br>
  <p>RITSEC is a student-run organization dedicated to educating and preparing RIT students to compete in security-related
  competitions, as well as showcasing RIT student talent in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for you.
  </p>
  <p>
  We believe security is for anyone who wants to learn and center our activities around multiple aspects of security. This includes
  live individual and team-based competitions, hands-on training, student run research, and sponsor talks. Our security exercises
  cover a wide variety of areas in computing security, including penetration testing, Windows and Linux server hardening,
  web security, network services, and more!</p>
  <p>In 2018, the Security Practices And Research Student Association (SPARSA) and RIT Competitive Cybersecurity Club (RC3) merged to become RITSEC.
  As a result, the security community at RIT became more unified as the major and industry grew.</p>
  <br><br><br><br>

#-------------------------------
# Events
events:
- name: Weekly Education Meeting
  description: >
    Join us every Friday, 12:00 PM - 2:00 PM for a presentation and hands-on
    lab to learn a new security topic! Labs are generally made up of multiple
    challenges of varying difficulty, and are intended to give members
    practical experience with the topics discussed in the week's presentation.
    Club members can earn points that accumulate over the semester for
    completing challenges. How high up on the leaderboard can YOU make it?
  image: meetings.png
- name: Weekly Research Meeting
  description: >
    Following the education section, RITSEC hosts a research section every
    Friday, 2:00 PM - 4:00 PM. Students are given the opportunity to present on
    security topics that interest them and any current projects they would like
    to share with the club. Please contact the Head of Research to submit a
    presentation.
  image: meetings.png
- name: RITSEC CTF
  description: >
    The RITSEC CTF is a <a href="https://ctftime.org/ctf-wtf/">Jeopardy-style
    CTF</a> hosted online for 60 hours in the late fall. Participation is open
    to all, and registered RIT teams are eligible for prizes! The CTF generally
    focuses on binary/RE, cryptography, forensics, progamming, and web security
    challenges. We welcome beginners and more advanced security friends alike!
  image: ists.jpg
- name: <a href="https://www.ists.io">ISTS</a>
  description: >
    The Information Security Talent Search is an annual three-day cyber
    attack/defend competition typically hosted in the early spring at RIT.
    Every year, competitors from both RIT and invited colleges from around the
    country are faced with a wide variety of challenges which are designed to
    cover as many facets of the security industry as possible. This includes
    defensive and offensive capabilities, system administration, software
    security, networking, programming, and much more! Challenges and activities
    include a CTF, King-of-the-Hill, policy writing, incident response, and
    code review -- all while defending a completely student-built
    infrastructure!
  image: ists.jpg
- name: IRSeC
  description: >
    The Incident Response Security Competition is our more beginner-friendly
    Red/Blue competition. IRSeC is typically hosted in the late spring at RIT.
    With IRSeC, we aim to provide RIT students with some initial defensive and
    incident response experience. IRSeC also features an entirely student-run
    Red Team comprised of RITSEC members.
  image: hacknights.jpg
