---
#-------------------------------
# General Site Settings

title: RITSEC
title_long: RITSEC Student Computing Security Club
motto: Security Through Community
email: ritsecclub@gmail.com
description: >
  RITSEC Student Computing Security Club
twitter: RITSECclub
github:
  name: ritsec
  project: ritsec.github.io
facebook_page: RITSEC
facebook_group: RITSEC.group
youtube: UCfakBry_pXOvaPrVVr1SH-Q

#-------------------------------
# Main Image Slider Settings
slider:
  - image: ISTS_0.jpg
  - image: IRSeC2019_photo.jpg
  - image: ISTS_1.jpg
  - image: ISTS_2.jpg
  - image: ISTS_4.jpg
#-------------------------------
# Navbar Settings
favicon: favicon.png
navbar-brand:
  image: logo_header.png
  link: "/index.html"

navbar:
  - name: "Home"
    link: "index.html"
  - name: "About"
    link: "about.html"
  - name: Members
    link: "eboard.html"
    subitems:
      - name: "EBoard"
        link: "eboard.html"
      - name: "Past EBoards"
        link: "past-eboards.html"
      - name: "Alumni"
        link: "alumni.html"
  - name: "Events"
    link: "events.html"
  - name: "Resources"
    link: "resources.html"
  - name: "Sponsors"
    link: "sponsors.html"

#-------------------------------
# EBoard Settings

eboard_roles:
  - name: President
    appointee: Shannon McHale
    image: ShannonBioPic.png
    contact: sxm6549@rit.edu
    description: >
      Shannon is a third-year computing security student. She has served as RC3 and RITSEC Treasurer and was also
      the Public Relations Head of Women in Computing. Shannon is currently a member of the RITSEC Red Team and does her best
      to attend as many free security conferences as possible. In her free time, Shannon tries to get to bed by 11pm
      and watches an insane amount of TV.
  - name: Director of Public Relations
    appointee: Adrianna Visca
    image: AdriannaBioPic.jpg
    contact: axv4486@rit.edu
    description: >
      Adrianna is a third-year Computing Security student with a minor in Networking. Outside of security,
      she is involved in RIT Orientation, RIT365, and Women in Computing. She's always open to talk about anything
      and everything, especially if the conversation includes pictures of dogs.
  - name: Head of Education
    appointee: Owen Siebert
    image: OwenBioPic.PNG
    contact: osiebert@mail.rit.edu
    description: >
      Owen in a fourth-year computing security student, native of Rochester. He enjoys networking, red teaming,
      and trying to make C2’s. Owen was previously the NextHop Treasurer, and can often be found working shifts in the
      cage - stop by and say hi. He will never say no to going out for a drink and is down to talk anything security,
      or otherwise.
  - name: Head of Research
    appointee: Ian Furr
    image: IanBioPic.jpg
    contact: isf6751@rit.edu
    description: >
      Ian is a fourth-year Computing Security student. Ian was previously the Vice President and Competition Director
      of NextHop, RITs Systems Administration & Networking Club. He loves Cyber Security Policy & Legislation, Disaster
      Recovery/Incident Response, Social Engineering, and the Internet of things. When he's not in the labs he can
      commonly be found hiking up a mountain, hanging in his hammock or out on his slackline.
  - name: "Competition Architect: ISTS & HackerThon"
    appointee: Jack "Hulto" McKenna
    image: JackBioPic.jpg
    contact: hulto@mail.rit.edu
    description: >
      "Hack the planet!"
      Popping boxes and teaching kiddos that's what it's all about. As ISTS CA I'm here to run some competitions and
      educate some folks. Hmu if you wanna help run ISTS or Hackerthon. If you're interested in competing
      or running your own competitions drop me a line.
  - name: "Competition Architect: IRSeC & CTF"
    appointee: Quintin Walters
    image: QuintinBioPic.jpg
    contact: qxk3054@rit.edu
    description: >
      Quintin is a fourth-year Computing Security student. He focuses on malware analysis, reverse engineering,
      and digital forensics. Outside of security Quintin enjoys reading, swimming, and playing Dungeons and Dragons.
  - name: Treasurer
    appointee: Amanda Brown
    image: AmandaBioPic.JPG
    contact: aeb6590@rit.edu
    description: >
      Amanda is a third-year computing security student. Her primary focus is in penetration testing and breaking
      things in fun ways. Amanda is on RIT’s CCDC team, serves as an ambassador for Golisano and Honors Program mentor,
      and is involved in Women in Computing. Outside of security, Amanda enjoys hiking with lots of sunscreen,
      traveling, and general tomfoolery.
  - name: Secretary
    appointee: Jon Bauer
    image: JonBioPic.jpg
    contact: jmb4371@rit.edu
    description: >
      Jon is a third-year computing security student with a minor in networking and systems administration.
      Relating to security Jon attends the weekly meets and is a part of the RITSEC Red Team. Currently his
      favorite subjects in security are operating systems and penetration testing.
      Outside of security he is also on the swimming and diving team and enjoys relaxing with friends.
  - name: Tech Lead
    appointee: Sunggwan Choi
    image: ChoiBioPic.jpg
    contact: sxc2679@rit.edu
    description: >
      Choi is a third-year Computing Security student, from Korea. As much as he is trying to learn computer languages,
      he is also trying to learn the English language as well. He doesn't have a specialization yet, he is just trying
      harder to learn new things everyday. And no, he is not from North Korea.
  - name: Operations Lead
    appointee: Evan Mikulski
    image: EvanBioPic.jpg
    contact: riprock@mail.rit.edu
    description: >
      Evan is a second year computing security student. His interests lie in Red Teaming, Forensics, and Homelabbing.
      You can find him in the Labs messing with something. Outside of CSEC he is a member of K2GXT, RIT’s
      amateur radio club. Feel free to go up and say hello if you see him. He will never turn down a chance to
      hang out or go get food.

#-------------------------------
# About Us

about_us_short: >
  <p>
  RITSEC is a student club dedicated to teaching "Security Through Community". RITSEC is dedicated to educating
  and preparing RIT students to compete in security-related competitions, as well as showcasing RIT student talent
  in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for
  you. All of the activities we host to promote this learning can be found on our 'Events' page.
  </p>
about_us_long: >
  RITSEC is a student club dedicated to teaching "Security Through Community". RITSEC is dedicated to educating
  and preparing RIT students to compete in security-related competitions, as well as showcasing RIT student talent
  in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for
  you. All of the activities we host to promote this learning can be found on our 'Events' page.
  <br><br>
  We believe security is for anyone who wants to learn and center our activities around multiple aspects of security.
  This includes live individual and team-based competitions, hands-on training, student run research, and sponsor talks.
  Our security exercises cover a wide variety of areas in computing security, including penetration testing,
  Windows and Linux server hardening,
  web security, network services, and more!

interest_groups:
  - name: RVAPT
    meeting_time: "Sunday from 2-3 pm in Air Gap"
    description: RIT Vulnerability Assessment and Penetration Testing
    contact: NA
  - name: Reversing Interest group
    meeting_time: "5 pm on Saturday in Seclabs"
    description: Learn about reverse engineering!
    contact: NA
  - name: Team Contagion
    meeting_time: "3:30 PM on Saturday in Seclab"
    description: This CTF Interest Group competes in Capture The Flag challenges.
    contact: NA
  - name: >-
      <a style="color:: black;" href="https://wicysrit.weebly.com/">WiCyS Student Chapter</a>
    meeting_time: Every other Tuesday 6-7pm Slaughter 2120 (even weeks)
    description: >-
      Women in Cybersecurity Student Chapter at RIT is an all-inclusive interest group dedicated to making RIT's computing security community a better environment for women.
      The chapter holds meetings and events for students to come together and share their passion for security while also creating a supportive network.
    contact: NA

#-------------------------------
# Events
events:
  - name: Weekly Education Meeting
    description: >
      Join us every Friday, 12:00 PM - 2:00 PM for a presentation and hands-on
      lab to learn a new security topic! Labs are generally made up of multiple
      challenges of varying difficulty, and are intended to give members
      practical experience with the topics discussed in the week's presentation.
      Club members can earn points that accumulate over the semester for
      completing challenges. How high up on the leaderboard can YOU make it?
    image: logo_header.png
  - name: Weekly Research Meeting
    description: >
      Following the education section, RITSEC hosts a research section every
      Friday, 2:00 PM - 4:00 PM. Students are given the opportunity to present on
      security topics that interest them and any current projects they would like
      to share with the club. Please contact the Head of Research to submit a
      presentation.
    image: logo_header.png
  - name: <a href="https://www.ists.io">ISTS</a>
    description: >
      The Information Security Talent Search is an annual three-day cyber
      attack/defend competition typically hosted in the early spring at RIT.
      Every year, competitors from both RIT and invited colleges from around the
      country are faced with a wide variety of challenges which are designed to
      cover as many facets of the security industry as possible. This includes
      defensive and offensive capabilities, system administration, software
      security, networking, programming, and much more! Challenges and activities
      include a CTF, King-of-the-Hill, policy writing, incident response, and
      code review -- all while defending a completely student-built
      infrastructure!
    image: ists.jpg
  - name: RITSEC CTF
    description: >
      The RITSEC CTF is a <a href="https://ctftime.org/ctf-wtf/">Jeopardy-style
      CTF</a> hosted online for 60 hours in the late fall. Participation is open
      to all, and registered RIT teams are eligible for prizes! The CTF generally
      focuses on binary/RE, cryptography, forensics, progamming, and web security
      challenges. We welcome beginners and more advanced security friends alike!
    image: ritsec-ctf18.png
  - name: IRSeC
    description: >
      The Incident Response Security Competition is our more beginner-friendly
      Red/Blue competition. IRSeC is typically hosted in the late spring at RIT.
      With IRSeC, we aim to provide RIT students with some initial defensive and
      incident response experience. IRSeC also features an entirely student-run
      Red Team comprised of RITSEC members.
    image: IRSEC_Logo.png
  - name: HackerThon
    description: >
      Our newest event in which we spend 24 hours creating a security related tool or project. 
      This is a great way for our members to find a side project or dedicate time to one they already have. 
      After the Hacker-Thon, our members present their work at the research portion of our meetings.
    image: HackerThon_Logo.png
